SET(SOURCES components/ui_comp_alarm_comp.c
    components/ui_comp_clock_dot.c
    components/ui_comp_scrolldots.c
    components/ui_comp_small_label.c
    components/ui_comp.c
    screens/ui_Splash.c
    screens/ui_Clock.c
    screens/ui_Call.c
    screens/ui_Music_Player.c
    screens/ui_Weather.c
    screens/ui_Alarm.c
    screens/ui_Today.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    images/ui_img_sls_logo_png.c
    images/ui_img_pattern_png.c
    images/ui_img_clock_min_png.c
    images/ui_img_clock_hour_png.c
    images/ui_img_clock_sec_png.c
    images/ui_img_phone_png.c
    images/ui_img_avatar_png.c
    images/ui_img_weather_1_png.c
    images/ui_img_weather_2_png.c
    images/ui_img_weather_3_png.c
    images/ui_img_environment_v3_assets.c
    images/ui_img_device_v3_assets.c
    images/ui_img_home_mascot.c
    images/ui_img_home_calendar.c
    images/ui_img_home_center_leaf.c
    images/ui_img_home_branch_corner.c
    images/ui_img_home_card_gloss.c
    images/ui_img_home_env_overlay.c
    images/ui_img_home_hum_icon.c
    images/ui_img_home_hum_plant.c
    images/ui_img_home_moon.c
    images/ui_img_home_paper_texture.c
    images/ui_img_home_sparkle_large.c
    images/ui_img_home_sparkle_small.c
    images/ui_img_home_temp_icon.c
    images/ui_img_home_temp_plant.c
    images/ui_img_home_time_halo.c
    images/ui_img_music_v3_assets.c
    images/ui_img_focus_mascot_ready.c
    images/ui_img_focus_mascot_running.c
    images/ui_img_focus_mascot_paused.c
    images/ui_img_focus_mascot_finished.c
    images/ui_img_focus_title_tomato.c
    images/ui_img_focus_sparkle_small.c
    images/ui_img_focus_sparkle_large.c
    images/ui_img_focus_orbit_glow.c
    images/ui_img_focus_orbit_trail.c
    images/ui_img_focus_paper_texture.c
    images/ui_img_focus_ring_overlay.c
    images/ui_img_focus_tomato_crown.c
    images/ui_img_focus_tomato_emblem.c
    images/ui_img_focus_corner_vine_right.c
    images/ui_img_focus_button_primary_overlay.c
    images/ui_img_focus_button_secondary_overlay.c
    fonts/ui_font_Number.c
    fonts/ui_font_FocusDigits.c
    fonts/ui_font_HomeTime.c
    fonts/ui_font_MusicTitle.c
    fonts/ui_font_MusicMeta.c)

add_library(ui ${SOURCES})
