SET(SOURCES components/ui_comp_alarm_comp.c
    components/ui_comp_clock_dot.c
    components/ui_comp_scrolldots.c
    components/ui_comp_small_label.c
    components/ui_comp.c
    screens/ui_Splash.c
    screens/ui_Clock.c
    screens/ui_Call.c
    screens/ui_Music_Player.c
    screens/ui_Weather.c
    screens/ui_Alarm.c
    screens/ui_Today.c
    ui.c
    components/ui_comp_hook.c
    ui_helpers.c
    images/ui_img_sls_logo_png.c
    images/ui_img_pattern_png.c
    images/ui_img_clock_min_png.c
    images/ui_img_clock_hour_png.c
    images/ui_img_clock_sec_png.c
    images/ui_img_phone_png.c
    images/ui_img_avatar_png.c
    images/ui_img_play_png.c
    images/ui_img_album_png.c
    images/ui_img_backward_png.c
    images/ui_img_forward_png.c
    images/ui_img_weather_1_png.c
    images/ui_img_weather_2_png.c
    images/ui_img_weather_3_png.c
    images/ui_img_home_mascot.c
    images/ui_img_home_corner_leaf.c
    images/ui_img_home_calendar.c
    images/ui_img_home_temperature.c
    images/ui_img_home_humidity.c
    images/ui_img_home_center_leaf.c
    images/ui_img_focus_mascot_ready.c
    images/ui_img_focus_mascot_running.c
    images/ui_img_focus_mascot_paused.c
    images/ui_img_focus_mascot_finished.c
    images/ui_img_focus_corner_vine.c
    images/ui_img_focus_left_decor_ready.c
    images/ui_img_focus_left_decor_running.c
    images/ui_img_focus_left_decor_paused.c
    images/ui_img_focus_left_decor_finished.c
    images/ui_img_focus_back.c
    images/ui_img_focus_gear.c
    images/ui_img_focus_edit.c
    images/ui_img_focus_leaf.c
    images/ui_img_focus_medal.c
    images/ui_img_focus_pause.c
    images/ui_img_focus_stop.c
    images/ui_img_focus_cup.c
    fonts/ui_font_Number.c)

add_library(ui ${SOURCES})
