// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"
#include "screens/ui_Clock.h"
#include "screens/ui_Call.h"
#include "screens/ui_Music_Player.h"
#include "screens/ui_Weather.h"
#include "screens/ui_Alarm.h"
#include "screens/ui_Device.h"
#include "screens/ui_Today.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * upanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_clock_min_png);    // assets/clock_min.png
LV_IMG_DECLARE(ui_img_clock_hour_png);    // assets/clock_hour.png
LV_IMG_DECLARE(ui_img_clock_sec_png);    // assets/clock_sec.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_avatar_png);    // assets/avatar.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png
LV_IMG_DECLARE(ui_img_environment_v3_topbar);
LV_IMG_DECLARE(ui_img_environment_v3_speech);
LV_IMG_DECLARE(ui_img_environment_v3_character);
LV_IMG_DECLARE(ui_img_environment_v3_hero);
LV_IMG_DECLARE(ui_img_environment_v3_temp_card);
LV_IMG_DECLARE(ui_img_environment_v3_humidity_card);
LV_IMG_DECLARE(ui_img_environment_v3_iaq_card);
LV_IMG_DECLARE(ui_img_environment_v3_pressure_card);
LV_IMG_DECLARE(ui_img_device_v3_bg);
LV_IMG_DECLARE(ui_img_device_v3_detail_bg);
LV_IMG_DECLARE(ui_img_device_v3_card_wave);
LV_IMG_DECLARE(ui_img_device_v3_corner_flower);
LV_IMG_DECLARE(ui_img_device_v3_header_left);
LV_IMG_DECLARE(ui_img_device_v3_header_right);
LV_IMG_DECLARE(ui_img_device_v3_bottom_banner);
LV_IMG_DECLARE(ui_img_device_v3_tab_active);
LV_IMG_DECLARE(ui_img_device_v3_pill_ok);
LV_IMG_DECLARE(ui_img_device_v3_pill_warning);
LV_IMG_DECLARE(ui_img_device_v3_pill_offline);
LV_IMG_DECLARE(ui_img_device_v3_icon_shield);
LV_IMG_DECLARE(ui_img_device_v3_icon_cloud);
LV_IMG_DECLARE(ui_img_device_v3_icon_environment);
LV_IMG_DECLARE(ui_img_device_v3_icon_speaker);
LV_IMG_DECLARE(ui_img_device_v3_icon_back);
LV_IMG_DECLARE(ui_img_device_v3_icon_arrow);
LV_IMG_DECLARE(ui_img_device_v3_icon_chip);
LV_IMG_DECLARE(ui_img_device_v3_icon_board);
LV_IMG_DECLARE(ui_img_device_v3_icon_firmware);
LV_IMG_DECLARE(ui_img_device_v3_icon_clock);
LV_IMG_DECLARE(ui_img_device_v3_icon_memory);
LV_IMG_DECLARE(ui_img_device_v3_icon_ota);
LV_IMG_DECLARE(ui_img_device_v3_icon_wifi);
LV_IMG_DECLARE(ui_img_device_v3_icon_router);
LV_IMG_DECLARE(ui_img_device_v3_icon_signal);
LV_IMG_DECLARE(ui_img_device_v3_icon_ip);
LV_IMG_DECLARE(ui_img_device_v3_icon_mqtt);
LV_IMG_DECLARE(ui_img_device_v3_icon_udp);
LV_IMG_DECLARE(ui_img_device_v3_icon_bme);
LV_IMG_DECLARE(ui_img_device_v3_icon_temperature);
LV_IMG_DECLARE(ui_img_device_v3_icon_humidity);
LV_IMG_DECLARE(ui_img_device_v3_icon_pressure);
LV_IMG_DECLARE(ui_img_device_v3_icon_iaq);
LV_IMG_DECLARE(ui_img_device_v3_icon_co2);
LV_IMG_DECLARE(ui_img_device_v3_icon_accuracy);
LV_IMG_DECLARE(ui_img_device_v3_icon_microphone);
LV_IMG_DECLARE(ui_img_device_v3_icon_decoder);
LV_IMG_DECLARE(ui_img_device_v3_icon_volume);
LV_IMG_DECLARE(ui_img_home_mascot);
LV_IMG_DECLARE(ui_img_home_corner_leaf);
LV_IMG_DECLARE(ui_img_home_calendar);
LV_IMG_DECLARE(ui_img_home_temperature);
LV_IMG_DECLARE(ui_img_home_humidity);
LV_IMG_DECLARE(ui_img_home_center_leaf);
LV_IMG_DECLARE(ui_img_home_branch_corner);
LV_IMG_DECLARE(ui_img_home_card_gloss);
LV_IMG_DECLARE(ui_img_home_env_overlay);
LV_IMG_DECLARE(ui_img_home_hum_icon);
LV_IMG_DECLARE(ui_img_home_hum_plant);
LV_IMG_DECLARE(ui_img_home_moon);
LV_IMG_DECLARE(ui_img_home_paper_texture);
LV_IMG_DECLARE(ui_img_home_sparkle_large);
LV_IMG_DECLARE(ui_img_home_sparkle_small);
LV_IMG_DECLARE(ui_img_home_temp_icon);
LV_IMG_DECLARE(ui_img_home_temp_plant);
LV_IMG_DECLARE(ui_img_home_time_halo);
LV_IMG_DECLARE(ui_img_music_v3_bg);
LV_IMG_DECLARE(ui_img_music_v3_album_cover);
LV_IMG_DECLARE(ui_img_music_v3_album_fade);
LV_IMG_DECLARE(ui_img_music_v3_album_frame);
LV_IMG_DECLARE(ui_img_music_v3_btn_list_bg);
LV_IMG_DECLARE(ui_img_music_v3_btn_play_bg);
LV_IMG_DECLARE(ui_img_music_v3_btn_small_bg);
LV_IMG_DECLARE(ui_img_music_v3_companion_loading);
LV_IMG_DECLARE(ui_img_music_v3_companion_paused);
LV_IMG_DECLARE(ui_img_music_v3_companion_playing);
LV_IMG_DECLARE(ui_img_music_v3_eq_01);
LV_IMG_DECLARE(ui_img_music_v3_eq_02);
LV_IMG_DECLARE(ui_img_music_v3_eq_03);
LV_IMG_DECLARE(ui_img_music_v3_eq_04);
LV_IMG_DECLARE(ui_img_music_v3_eq_05);
LV_IMG_DECLARE(ui_img_music_v3_eq_06);
LV_IMG_DECLARE(ui_img_music_v3_eq_07);
LV_IMG_DECLARE(ui_img_music_v3_eq_08);
LV_IMG_DECLARE(ui_img_music_v3_eq_09);
LV_IMG_DECLARE(ui_img_music_v3_eq_10);
LV_IMG_DECLARE(ui_img_music_v3_eq_11);
LV_IMG_DECLARE(ui_img_music_v3_eq_12);
LV_IMG_DECLARE(ui_img_music_v3_loading_01);
LV_IMG_DECLARE(ui_img_music_v3_loading_02);
LV_IMG_DECLARE(ui_img_music_v3_loading_03);
LV_IMG_DECLARE(ui_img_music_v3_loading_04);
LV_IMG_DECLARE(ui_img_music_v3_loading_05);
LV_IMG_DECLARE(ui_img_music_v3_loading_06);
LV_IMG_DECLARE(ui_img_music_v3_icon_leaf);
LV_IMG_DECLARE(ui_img_music_v3_icon_list);
LV_IMG_DECLARE(ui_img_music_v3_icon_note);
LV_IMG_DECLARE(ui_img_music_v3_icon_next);
LV_IMG_DECLARE(ui_img_music_v3_icon_pause);
LV_IMG_DECLARE(ui_img_music_v3_icon_play);
LV_IMG_DECLARE(ui_img_music_v3_icon_prev);
LV_IMG_DECLARE(ui_img_music_v3_status_bg);
LV_IMG_DECLARE(ui_img_music_v3_status_loading);
LV_IMG_DECLARE(ui_img_music_v3_status_paused);
LV_IMG_DECLARE(ui_img_music_v3_status_playing);
LV_IMG_DECLARE(ui_img_focus_mascot_ready);
LV_IMG_DECLARE(ui_img_focus_mascot_running);
LV_IMG_DECLARE(ui_img_focus_mascot_paused);
LV_IMG_DECLARE(ui_img_focus_mascot_finished);
LV_IMG_DECLARE(ui_img_focus_title_tomato);
LV_IMG_DECLARE(ui_img_focus_tomato_watermark);
LV_IMG_DECLARE(ui_img_focus_sparkle_small);
LV_IMG_DECLARE(ui_img_focus_sparkle_large);
LV_IMG_DECLARE(ui_img_focus_orbit_glow);
LV_IMG_DECLARE(ui_img_focus_corner_vine);
LV_IMG_DECLARE(ui_img_focus_left_decor_ready);
LV_IMG_DECLARE(ui_img_focus_left_decor_running);
LV_IMG_DECLARE(ui_img_focus_left_decor_paused);
LV_IMG_DECLARE(ui_img_focus_left_decor_finished);
LV_IMG_DECLARE(ui_img_focus_back);
LV_IMG_DECLARE(ui_img_focus_gear);
LV_IMG_DECLARE(ui_img_focus_edit);
LV_IMG_DECLARE(ui_img_focus_leaf);
LV_IMG_DECLARE(ui_img_focus_medal);
LV_IMG_DECLARE(ui_img_focus_pause);
LV_IMG_DECLARE(ui_img_focus_stop);
LV_IMG_DECLARE(ui_img_focus_cup);
LV_IMG_DECLARE(ui_img_focus_button_primary_overlay);
LV_IMG_DECLARE(ui_img_focus_button_secondary_overlay);
LV_IMG_DECLARE(ui_img_focus_corner_vine_right);
LV_IMG_DECLARE(ui_img_focus_orbit_trail);
LV_IMG_DECLARE(ui_img_focus_paper_texture);
LV_IMG_DECLARE(ui_img_focus_ring_overlay);
LV_IMG_DECLARE(ui_img_focus_tomato_crown);
LV_IMG_DECLARE(ui_img_focus_tomato_emblem);

// FONTS
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_HomeTime);
LV_FONT_DECLARE(ui_font_MusicTitle);
LV_FONT_DECLARE(ui_font_MusicMeta);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
