// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"
#include "screens/ui_Clock.h"
#include "screens/ui_Call.h"
#include "screens/ui_Music_Player.h"
#include "screens/ui_Weather.h"
#include "screens/ui_Alarm.h"
#include "screens/ui_Device.h"
#include "screens/ui_Today.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * upanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * min_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_clock_min_png);    // assets/clock_min.png
LV_IMG_DECLARE(ui_img_clock_hour_png);    // assets/clock_hour.png
LV_IMG_DECLARE(ui_img_clock_sec_png);    // assets/clock_sec.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_avatar_png);    // assets/avatar.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png
LV_IMG_DECLARE(ui_img_home_mascot);
LV_IMG_DECLARE(ui_img_home_corner_leaf);
LV_IMG_DECLARE(ui_img_home_calendar);
LV_IMG_DECLARE(ui_img_home_temperature);
LV_IMG_DECLARE(ui_img_home_humidity);
LV_IMG_DECLARE(ui_img_home_center_leaf);
LV_IMG_DECLARE(ui_img_focus_mascot_ready);
LV_IMG_DECLARE(ui_img_focus_mascot_running);
LV_IMG_DECLARE(ui_img_focus_mascot_paused);
LV_IMG_DECLARE(ui_img_focus_mascot_finished);
LV_IMG_DECLARE(ui_img_focus_corner_vine);
LV_IMG_DECLARE(ui_img_focus_left_decor_ready);
LV_IMG_DECLARE(ui_img_focus_left_decor_running);
LV_IMG_DECLARE(ui_img_focus_left_decor_paused);
LV_IMG_DECLARE(ui_img_focus_left_decor_finished);
LV_IMG_DECLARE(ui_img_focus_back);
LV_IMG_DECLARE(ui_img_focus_gear);
LV_IMG_DECLARE(ui_img_focus_edit);
LV_IMG_DECLARE(ui_img_focus_leaf);
LV_IMG_DECLARE(ui_img_focus_medal);
LV_IMG_DECLARE(ui_img_focus_pause);
LV_IMG_DECLARE(ui_img_focus_stop);
LV_IMG_DECLARE(ui_img_focus_cup);

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
