#pragma once

/*
 * Pomodoro / focus screen design tokens.
 * Target: ESP32-C5 + LVGL 9.2, logical canvas 284 x 240.
 * The layout intentionally follows the real landscape panel instead of a phone aspect ratio.
 */

#define FOCUS_SCREEN_W 284
#define FOCUS_SCREEN_H 240

/* Header + main card */
#define FOCUS_HEADER_H 27
#define FOCUS_CARD_X 4
#define FOCUS_CARD_Y 28
#define FOCUS_CARD_W 276
#define FOCUS_CARD_H 150
#define FOCUS_CARD_RADIUS 17

/* Main timer orbit */
#define FOCUS_TIMER_X 62
#define FOCUS_TIMER_Y 33
#define FOCUS_TIMER_SIZE 146
#define FOCUS_TIMER_INNER_X 73
#define FOCUS_TIMER_INNER_Y 44
#define FOCUS_TIMER_INNER_SIZE 124
#define FOCUS_ARC_MAIN_WIDTH 5
#define FOCUS_ARC_INDICATOR_WIDTH 8
#define FOCUS_ARC_START_DEG 135
#define FOCUS_ARC_SPAN_DEG 300

/* Bottom controls */
#define FOCUS_LEFT_BTN_X 6
#define FOCUS_LEFT_BTN_Y 184
#define FOCUS_LEFT_BTN_W 76
#define FOCUS_LEFT_BTN_H 46

#define FOCUS_MAIN_BTN_X 88
#define FOCUS_MAIN_BTN_Y 181
#define FOCUS_MAIN_BTN_W 108
#define FOCUS_MAIN_BTN_H 52

#define FOCUS_RIGHT_BTN_X 202
#define FOCUS_RIGHT_BTN_Y 184
#define FOCUS_RIGHT_BTN_W 76
#define FOCUS_RIGHT_BTN_H 46

/* Existing mascot assets are 88 x 112 and already have state variants. */
#define FOCUS_MASCOT_RIGHT_X 202
#define FOCUS_MASCOT_RIGHT_Y 66
#define FOCUS_MASCOT_LEFT_X 202
#define FOCUS_MASCOT_LEFT_Y 66
#define FOCUS_MASCOT_SAFE_W 82
#define FOCUS_MASCOT_SAFE_H 112
#define FOCUS_BUTTON_SAFE_Y_MIN 181

#define FOCUS_PAGE_DOTS_Y 7

/* Cream + sage palette */
#define FOCUS_COLOR_TEXT_MAIN 0x3F582C
#define FOCUS_COLOR_TEXT_GREEN 0x526D3E
#define FOCUS_COLOR_TEXT_MUTED 0x8B9471
#define FOCUS_COLOR_PANEL 0xFFFCF1
#define FOCUS_COLOR_PANEL_BORDER 0xB9C98A
#define FOCUS_COLOR_TRACK 0xE2E3C8
#define FOCUS_COLOR_DECOR_BLUE 0xC8D9C5
#define FOCUS_COLOR_DECOR_GREEN 0x91AE59
#define FOCUS_COLOR_DECOR_YELLOW 0xE8D779

#define FOCUS_COLOR_READY_BG 0xFBF5E6
#define FOCUS_COLOR_READY_ACCENT 0x88A74E
#define FOCUS_COLOR_READY_PRIMARY 0x708E3D
#define FOCUS_COLOR_READY_SECONDARY 0xFFF9E9
#define FOCUS_COLOR_READY_LEFT 0xFFF9E9

#define FOCUS_COLOR_RUNNING_BG 0xFBF5E6
#define FOCUS_COLOR_RUNNING_ACCENT 0x91AE4F
#define FOCUS_COLOR_RUNNING_PRIMARY 0x6F8F3B
#define FOCUS_COLOR_RUNNING_SECONDARY 0xFFF9E9
#define FOCUS_COLOR_RUNNING_LEFT 0xFFF9E9

#define FOCUS_COLOR_PAUSED_BG 0xF8F3E8
#define FOCUS_COLOR_PAUSED_ACCENT 0x87936C
#define FOCUS_COLOR_PAUSED_PRIMARY 0x6E7E52
#define FOCUS_COLOR_PAUSED_SECONDARY 0xFFF9E9
#define FOCUS_COLOR_PAUSED_LEFT 0xFFF9E9

#define FOCUS_COLOR_FINISHED_BG 0xFCF6DF
#define FOCUS_COLOR_FINISHED_ACCENT 0xA6BE44
#define FOCUS_COLOR_FINISHED_PRIMARY 0x779937
#define FOCUS_COLOR_FINISHED_SECONDARY 0xFFF9E9
#define FOCUS_COLOR_FINISHED_LEFT 0xFFF9E9
