#pragma once

#define FOCUS_SCREEN_W 284
#define FOCUS_SCREEN_H 240

#define FOCUS_TIMER_X 66
#define FOCUS_TIMER_Y 6
#define FOCUS_TIMER_SIZE 152
#define FOCUS_TIMER_INNER_X 76
#define FOCUS_TIMER_INNER_Y 16
#define FOCUS_TIMER_INNER_SIZE 132
#define FOCUS_ARC_MAIN_WIDTH 4
#define FOCUS_ARC_INDICATOR_WIDTH 5

#define FOCUS_LEFT_BTN_X 7
#define FOCUS_LEFT_BTN_Y 163
#define FOCUS_LEFT_BTN_W 77
#define FOCUS_LEFT_BTN_H 56

#define FOCUS_MAIN_BTN_X 91
#define FOCUS_MAIN_BTN_Y 159
#define FOCUS_MAIN_BTN_W 102
#define FOCUS_MAIN_BTN_H 63

#define FOCUS_RIGHT_BTN_X 200
#define FOCUS_RIGHT_BTN_Y 163
#define FOCUS_RIGHT_BTN_W 77
#define FOCUS_RIGHT_BTN_H 56

#define FOCUS_MASCOT_RIGHT_X 202
#define FOCUS_MASCOT_RIGHT_Y 6
#define FOCUS_MASCOT_LEFT_X 0
#define FOCUS_MASCOT_LEFT_Y 0
#define FOCUS_MASCOT_SAFE_W 88
#define FOCUS_MASCOT_SAFE_H 112
#define FOCUS_BUTTON_SAFE_Y_MIN 154

#define FOCUS_PAGE_DOTS_Y 229

#define FOCUS_COLOR_TEXT_MAIN 0x61442F
#define FOCUS_COLOR_TEXT_GREEN 0x486A3B
#define FOCUS_COLOR_TEXT_MUTED 0x8F745A
#define FOCUS_COLOR_PANEL 0xFFFDF8
#define FOCUS_COLOR_PANEL_BORDER 0xE9DAB8
#define FOCUS_COLOR_TRACK 0xD9C9A7
#define FOCUS_COLOR_DECOR_BLUE 0xA9CEE5
#define FOCUS_COLOR_DECOR_GREEN 0x6EA16A
#define FOCUS_COLOR_DECOR_YELLOW 0xF1BB58

#define FOCUS_COLOR_READY_BG 0xFBF7EF
#define FOCUS_COLOR_READY_ACCENT 0x76975E
#define FOCUS_COLOR_READY_PRIMARY 0x76975E
#define FOCUS_COLOR_READY_SECONDARY 0xFFFDF8
#define FOCUS_COLOR_READY_LEFT 0xEEF4DE

#define FOCUS_COLOR_RUNNING_BG 0xFBF7EF
#define FOCUS_COLOR_RUNNING_ACCENT 0x76975E
#define FOCUS_COLOR_RUNNING_PRIMARY 0xFFFDF8
#define FOCUS_COLOR_RUNNING_SECONDARY 0xEEF4DE
#define FOCUS_COLOR_RUNNING_LEFT 0xEEF4DE

#define FOCUS_COLOR_PAUSED_BG 0xFBF7EF
#define FOCUS_COLOR_PAUSED_ACCENT 0xE99A49
#define FOCUS_COLOR_PAUSED_PRIMARY 0xE99A49
#define FOCUS_COLOR_PAUSED_SECONDARY 0xFFFDF8
#define FOCUS_COLOR_PAUSED_LEFT 0xEEF4DE

#define FOCUS_COLOR_FINISHED_BG 0xFBF7EF
#define FOCUS_COLOR_FINISHED_ACCENT 0x76975E
#define FOCUS_COLOR_FINISHED_PRIMARY 0x76975E
#define FOCUS_COLOR_FINISHED_SECONDARY 0xFFFDF8
#define FOCUS_COLOR_FINISHED_LEFT 0xEEF4DE
