#pragma once

// Pomodoro V3 geometry. Values are copied from focus_ui_v3_manifest.json.
#define FOCUS_SCREEN_W 284
#define FOCUS_SCREEN_H 240

#define FOCUS_HEADER_ICON_X 10
#define FOCUS_HEADER_ICON_Y 6
#define FOCUS_HEADER_ICON_W 24
#define FOCUS_HEADER_ICON_H 24
#define FOCUS_TITLE_X 38
#define FOCUS_TITLE_Y 7
#define FOCUS_TITLE_W 62
#define FOCUS_TITLE_H 24

#define FOCUS_HEADER_STATE_X 104
#define FOCUS_HEADER_STATE_Y 5
#define FOCUS_HEADER_STATE_W 78
#define FOCUS_HEADER_STATE_H 25
#define FOCUS_HEADER_EMBLEM_ZOOM 112

#define FOCUS_SESSION_X 230
#define FOCUS_SESSION_Y 3
#define FOCUS_SESSION_W 43
#define FOCUS_SESSION_H 29

#define FOCUS_MAIN_PANEL_X 5
#define FOCUS_MAIN_PANEL_Y 34
#define FOCUS_MAIN_PANEL_W 274
#define FOCUS_MAIN_PANEL_H 162
#define FOCUS_MAIN_PANEL_RADIUS 18

#define FOCUS_ARC_CENTER_X 116
#define FOCUS_ARC_CENTER_Y 115
#define FOCUS_ARC_RADIUS 66
#define FOCUS_ARC_SIZE 132
#define FOCUS_ARC_X 50
#define FOCUS_ARC_Y 49
#define FOCUS_ARC_LINE_WIDTH 8
#define FOCUS_ARC_START_DEG 130
#define FOCUS_ARC_END_DEG 410
#define FOCUS_ARC_PROGRESS_MAX_VALUE 714

#define FOCUS_RING_OVERLAY_X 44
#define FOCUS_RING_OVERLAY_Y 43
#define FOCUS_RING_OVERLAY_W 144
#define FOCUS_RING_OVERLAY_H 144

#define FOCUS_CROWN_X 77
#define FOCUS_CROWN_Y 41
#define FOCUS_CROWN_W 78
#define FOCUS_CROWN_H 36

#define FOCUS_TIMER_CENTER_X 116
#define FOCUS_TIMER_Y 88
#define FOCUS_TIMER_W 122
#define FOCUS_TIMER_X 55
#define FOCUS_TIMER_ZOOM 256

#define FOCUS_PERIOD_X 80
#define FOCUS_PERIOD_Y 139
#define FOCUS_PERIOD_W 72
#define FOCUS_PERIOD_H 20

#define FOCUS_MASCOT_X 190
#define FOCUS_MASCOT_Y 84
#define FOCUS_MASCOT_W 88
#define FOCUS_MASCOT_H 110
#define FOCUS_MASCOT_RIGHT_X FOCUS_MASCOT_X
#define FOCUS_MASCOT_RIGHT_Y FOCUS_MASCOT_Y
#define FOCUS_MASCOT_LEFT_X FOCUS_MASCOT_X
#define FOCUS_MASCOT_LEFT_Y FOCUS_MASCOT_Y

#define FOCUS_CORNER_VINE_X 230
#define FOCUS_CORNER_VINE_Y 35
#define FOCUS_SPARKLE_LARGE_X 180
#define FOCUS_SPARKLE_LARGE_Y 53
#define FOCUS_SPARKLE_SMALL_X 178
#define FOCUS_SPARKLE_SMALL_Y 72

#define FOCUS_LEFT_BTN_X 8
#define FOCUS_LEFT_BTN_Y 202
#define FOCUS_LEFT_BTN_W 78
#define FOCUS_LEFT_BTN_H 32
#define FOCUS_MAIN_BTN_X 91
#define FOCUS_MAIN_BTN_Y 199
#define FOCUS_MAIN_BTN_W 102
#define FOCUS_MAIN_BTN_H 37
#define FOCUS_RIGHT_BTN_X 198
#define FOCUS_RIGHT_BTN_Y 202
#define FOCUS_RIGHT_BTN_W 78
#define FOCUS_RIGHT_BTN_H 32

#define FOCUS_PAPER_TEXTURE_OPA 32
#define FOCUS_MASCOT_FLOAT_PX 2
#define FOCUS_ORBIT_GLOW_MAX_ZOOM 277
#define FOCUS_BUTTON_PRESSED_ZOOM 248

// Palette copied from focus_ui_v3_manifest.json.
#define FOCUS_COLOR_BACKGROUND 0xFFF8E3
#define FOCUS_COLOR_PANEL 0xFFFCEF
#define FOCUS_COLOR_DEEP_GREEN 0x34532D
#define FOCUS_COLOR_LEAF_GREEN 0x719D49
#define FOCUS_COLOR_CORAL_TOMATO 0xE1673E
#define FOCUS_COLOR_CREAM_TRACK 0xECDDBE
#define FOCUS_COLOR_BROWN_TEXT 0x53412A
#define FOCUS_COLOR_PRIMARY_CREAM 0xFAEFD5
#define FOCUS_COLOR_BUTTON_GREEN 0xEEF4D8
#define FOCUS_COLOR_WHITE 0xFFFFFF

// Compatibility aliases used by the existing state renderer.
#define FOCUS_COLOR_TEXT_MAIN FOCUS_COLOR_DEEP_GREEN
#define FOCUS_COLOR_TEXT_GREEN FOCUS_COLOR_DEEP_GREEN
#define FOCUS_COLOR_TEXT_MUTED FOCUS_COLOR_BROWN_TEXT
#define FOCUS_COLOR_PANEL_BORDER FOCUS_COLOR_CREAM_TRACK
#define FOCUS_COLOR_TRACK FOCUS_COLOR_CREAM_TRACK
#define FOCUS_COLOR_LIME_GLOW FOCUS_COLOR_CORAL_TOMATO

#define FOCUS_COLOR_READY_BG FOCUS_COLOR_BACKGROUND
#define FOCUS_COLOR_READY_ACCENT FOCUS_COLOR_CORAL_TOMATO
#define FOCUS_COLOR_READY_PRIMARY FOCUS_COLOR_PRIMARY_CREAM
#define FOCUS_COLOR_READY_SECONDARY FOCUS_COLOR_BUTTON_GREEN
#define FOCUS_COLOR_READY_LEFT FOCUS_COLOR_BUTTON_GREEN

#define FOCUS_COLOR_RUNNING_BG FOCUS_COLOR_BACKGROUND
#define FOCUS_COLOR_RUNNING_ACCENT FOCUS_COLOR_CORAL_TOMATO
#define FOCUS_COLOR_RUNNING_PRIMARY FOCUS_COLOR_PRIMARY_CREAM
#define FOCUS_COLOR_RUNNING_SECONDARY FOCUS_COLOR_BUTTON_GREEN
#define FOCUS_COLOR_RUNNING_LEFT FOCUS_COLOR_BUTTON_GREEN

#define FOCUS_COLOR_PAUSED_BG FOCUS_COLOR_BACKGROUND
#define FOCUS_COLOR_PAUSED_ACCENT FOCUS_COLOR_CORAL_TOMATO
#define FOCUS_COLOR_PAUSED_PRIMARY FOCUS_COLOR_PRIMARY_CREAM
#define FOCUS_COLOR_PAUSED_SECONDARY FOCUS_COLOR_BUTTON_GREEN
#define FOCUS_COLOR_PAUSED_LEFT FOCUS_COLOR_BUTTON_GREEN

#define FOCUS_COLOR_FINISHED_BG FOCUS_COLOR_BACKGROUND
#define FOCUS_COLOR_FINISHED_ACCENT FOCUS_COLOR_CORAL_TOMATO
#define FOCUS_COLOR_FINISHED_PRIMARY FOCUS_COLOR_PRIMARY_CREAM
#define FOCUS_COLOR_FINISHED_SECONDARY FOCUS_COLOR_BUTTON_GREEN
#define FOCUS_COLOR_FINISHED_LEFT FOCUS_COLOR_BUTTON_GREEN
