#pragma once

#define HOME_SCREEN_W 284
#define HOME_SCREEN_H 240

#define HOME_COLOR_BG 0xFBF7EF
#define HOME_COLOR_CARD 0xFFFCF7
#define HOME_COLOR_CARD_BORDER 0xF1D9AE
#define HOME_COLOR_CARD_SHADOW 0xD8C08D
#define HOME_COLOR_TIME 0x4B3529
#define HOME_COLOR_DATE 0x9A6A38
#define HOME_COLOR_GREEN 0x6E9B52
#define HOME_COLOR_TEMP_BG 0xEDF6FB
#define HOME_COLOR_TEMP_BORDER 0xBDD4E5
#define HOME_COLOR_TEMP_TEXT 0x315D8D
#define HOME_COLOR_HUM_BG 0xF1F7E8
#define HOME_COLOR_HUM_BORDER 0xC7D8A8
#define HOME_COLOR_HUM_TEXT 0x3E7146
#define HOME_COLOR_PLUS 0xFFFFFF
#define HOME_COLOR_DECOR_YELLOW 0xFFE0A3
#define HOME_COLOR_DECOR_GREEN 0xCFE8D4
#define HOME_COLOR_DECOR_DOT_1 0xFFC967
#define HOME_COLOR_DECOR_DOT_2 0x9FC67E
#define HOME_COLOR_DECOR_DOT_3 0xB9D4F1
#define HOME_COLOR_DECOR_DOT_4 0x7FA467

#define HOME_CARD_X 14
#define HOME_CARD_Y 34
#define HOME_CARD_W 256
#define HOME_CARD_H 192
#define HOME_CARD_RADIUS 24

#define HOME_MASCOT_X 4
#define HOME_MASCOT_Y 1
#define HOME_CORNER_LEAF_X 226
#define HOME_CORNER_LEAF_Y 0

#define HOME_DATE_ICON_X 58
#define HOME_DATE_ICON_Y 16
#define HOME_DATE_X 88
#define HOME_DATE_Y 15
#define HOME_DATE_W 126

#define HOME_TIME_X 12
#define HOME_TIME_Y 53
#define HOME_TIME_W 232

#define HOME_STATUS_LEAF_X 114
#define HOME_STATUS_LEAF_Y 101
#define HOME_STATUS_X 46
#define HOME_STATUS_Y 121
#define HOME_STATUS_W 164

#define HOME_PILL_Y 151
#define HOME_PILL_W 111
#define HOME_PILL_H 33
#define HOME_PILL_RADIUS 17
#define HOME_TEMP_PILL_X 11
#define HOME_HUM_PILL_X 134
#define HOME_PILL_ICON_X 9
#define HOME_PILL_ICON_Y 4
#define HOME_PILL_LABEL_X 34
#define HOME_PILL_LABEL_Y 8
#define HOME_PILL_LABEL_W 72
