#pragma once

// Home clock V3 geometry copied from home_clock_v3_manifest.json.
#define HOME_SCREEN_W 284
#define HOME_SCREEN_H 240

#define HOME_CARD_X 10
#define HOME_CARD_Y 33
#define HOME_CARD_W 264
#define HOME_CARD_H 192
#define HOME_CARD_RADIUS 22

#define HOME_MASCOT_X 12
#define HOME_MASCOT_Y 0
#define HOME_BRANCH_X 198
#define HOME_BRANCH_Y 0

#define HOME_DATE_X 82
#define HOME_DATE_Y 46
#define HOME_DATE_W 120
#define HOME_DATE_H 24
#define HOME_DATE_ICON_X 90
#define HOME_DATE_ICON_Y 47
#define HOME_DATE_TEXT_X 116
#define HOME_DATE_TEXT_Y 50
#define HOME_DATE_TEXT_W 80

#define HOME_TIME_HALO_X 58
#define HOME_TIME_HALO_Y 58
#define HOME_TIME_HALO_W 176
#define HOME_TIME_HALO_H 96
#define HOME_TIME_X 28
#define HOME_TIME_Y 81
#define HOME_TIME_W 228
#define HOME_TIME_H 64

#define HOME_MOON_X 212
#define HOME_MOON_Y 88

#define HOME_STATUS_LEAF_X 106
#define HOME_STATUS_LEAF_Y 145
#define HOME_STATUS_X 131
#define HOME_STATUS_Y 143
#define HOME_STATUS_W 84
#define HOME_STATUS_H 22

#define HOME_TEMP_CARD_X 25
#define HOME_HUM_CARD_X 158
#define HOME_ENV_CARD_Y 172
#define HOME_ENV_CARD_W 101
#define HOME_ENV_CARD_H 36

#define HOME_TEMP_ICON_X 31
#define HOME_HUM_ICON_X 164
#define HOME_ENV_ICON_Y 179
#define HOME_TEMP_TITLE_X 56
#define HOME_HUM_TITLE_X 189
#define HOME_ENV_TITLE_Y 176
#define HOME_ENV_TITLE_W 42
#define HOME_TEMP_VALUE_X 56
#define HOME_HUM_VALUE_X 189
#define HOME_ENV_VALUE_Y 191
#define HOME_ENV_VALUE_W 56

#define HOME_TEMP_PLANT_X 95
#define HOME_TEMP_PLANT_Y 164
#define HOME_HUM_PLANT_X 229
#define HOME_HUM_PLANT_Y 163

#define HOME_SPARKLE_LARGE_X 208
#define HOME_SPARKLE_LARGE_Y 46
#define HOME_SPARKLE_SMALL_X 213
#define HOME_SPARKLE_SMALL_Y 151

#define HOME_PAGE_DOTS_Y 232

#define HOME_MASCOT_FLOAT_PX 1
#define HOME_BRANCH_ROTATION_TENTH_DEG 20
#define HOME_HALO_OPA_MIN 153
#define HOME_HALO_OPA_MAX 224
#define HOME_TIME_TRANSITION_Y 5

#define HOME_COLOR_BG 0xF6E8C5
#define HOME_COLOR_CARD 0xFFFCEF
#define HOME_COLOR_CARD_BORDER 0xE1C784
#define HOME_COLOR_CARD_SHADOW 0xB99954
#define HOME_COLOR_TIME 0x53412A
#define HOME_COLOR_DATE 0x7C5B2D
#define HOME_COLOR_GREEN 0x719D49
#define HOME_COLOR_TEMP_TEXT 0x438DC1
#define HOME_COLOR_HUM_TEXT 0x5B914D
#define HOME_COLOR_ENV_BG 0xFFFDF3
#define HOME_COLOR_ENV_BORDER 0xE8D8AF
#define HOME_COLOR_PAGE_DOT 0x719D49
#define HOME_COLOR_PAGE_DOT_IDLE 0xD9CBA7
#define HOME_COLOR_DECOR_GOLD 0xDDBB69
#define HOME_COLOR_DECOR_GREEN 0xC9DDB8
